### ISSUE TITLE
Tabulate issues

### ISSUE THREAD

**Issue by kevindavisross** [dlsun/symbulate#23]

**Comment by kevindavisross** [comment]
I've attached a .pdf with some issues I've encountered while using .tabulate()
[Tabulate issues.pdf](https://github.com/dlsun/symbulate/files/1170768/Tabulate.issues.pdf)

**Comment by dlsun** [comment]
I've just submitted a pull request that fixes the ordering of the outcomes when normalize=True. I think that everything else is working as intended:

- Python doesn't allow you to include unnamed arguments *after* a named argument to a function.
- For the `xy_pairs` example, the outcomes are actually tuples, i.e., `[(0,0), (0,1), (1,0), (1,1)]`, not lists. Although tuples behave like lists in many ways, they have the benefit of being hashable, which allows them to be put into Python dicts.
