### ISSUE TITLE
Allow .apply() for .draw()?

### ISSUE THREAD

**Issue by kevindavisross** [dlsun/symbulate#27]
Is there a reason why .apply() cannot be used with .draw()?

P = BoxModel([1, 0], size = 5)
P.draw().apply(sum)

returns an error

P.sim(1).apply(sum)

works and achieves the same result, But it would be nice if .draw().apply() could work for consistency,

**Comment by dlsun** [comment]
I think the current behavior is current. The idea of `.apply()` is to apply some function to *every* simulation in a set of simulations.

But if you call `.draw()`, then the result is just one simulation. So if you want to apply a function to the outcome, you should do so directly, e.g., `sum(P.draw())`.

**Comment by kevindavisross** [comment]
Sounds reasonable, so I'll close this.
