### ISSUE TITLE
xlim is inf for T and F

### ISSUE THREAD

**Issue by dlsun** [dlsun/symbulate#3]
When I run the code below

```
f = RV(F(5, 2))
f.sim(1000).plot()
```

I get the RuntimeWarning: invalid value encountered in double_scalars

This is because self.xlim is being set to inf, since by default, self.xlim is set to mean +/- 3*SD, and this distribution has infinite SD. Can we add some code to check for this case and set self.xlim to something finite?

**Comment by cenonn** [comment]
Is checking to see if the degrees of freedom lead to defined means and variances and directly checking if they are defined the same thing in this situation? 

Since xlim is being set to inf, what is matplotlib defaulting to using for the limit? I'm thinking of setting it to whatever the default value is, but I haven't been able to find it in the documentation.

**Comment by dlsun** [comment]
xlim is defined to be mean +/- 3 * SDs for all distributions, by default. This is a problem when mean or SD are inf. I would add a check there.

But perhaps we should change this default behavior. Maybe we should have it be the 1% and 99% quantiles of the distribution instead? Unlike the mean and SDs, these are always guaranteed to be defined.

**Comment by cenonn** [comment]
I changed the xlim to be 
```self.xlim = (
scipy.ppf(0.01, **self.params), 
scipy.ppf(0.99, **self.params))
```
The runtime error does go away. Should we assume that the user would know they would be simulating from a distribution with undefined or infinite mean and variance?

**Comment by dlsun** [comment]
I think that xlim should always be based on quantiles, which are always finite.

My only concern is how this looks. Could you see try all the different distributions and make sure that using the 1% and 99% quantiles as xlim looks appealing visually?

**Comment by cenonn** [comment]
The plots still look fine in most cases, about the same as before. The only time they look a bit odd is when we have infinite variance or undefined mean.

**Comment by cenonn** [comment]
This may need to be looked at again with some of the new distributions for week 2. So far I've added in Cauchy and Log-Normal and the plots are not exactly useful. They look the same when I do the same simulations in R though.

**Comment by kevindavisross** [comment]
Distributions like Cauchy, lognormal, t, etc have heavy-tails: P(|X| > t) goes to 0 slowly as t approaches infinity.  So when you run a simulation, there is a non-negligible probability that you get a few extreme outliers that throw off the whole scale of the plot.  It's just in the nature of these distributions; I don't know if there is a good "fix".  One option would be to allow plots with a log-scale on the x-axis, though that doesn't work when values of the RV can be negative.  Could we also pass xmin and xmax through .plot(), like .plot(xmax = 10)?  Or is there a good way to combine .filter() and .plot() to zoom in on a histogram with the bins adjusting when you zoom?

**Comment by dlsun** [comment]
This problem seems to be fixed. 

You can pass `xlim=` to `.plot()` for a distribution, but you can't do it for plots of simulations.
