### ISSUE TITLE
Histogram normalize=False option should return bin counts for Continuous RV. Change 'normed' kwarg to 'density' since normed is depricated

### ISSUE THREAD

**Issue by hayate0304** [dlsun/symbulate#68]
Hi professors,

I found the problem in the results.py file and I tried to fix it. How do I test if my correction is correct?

**Comment by hayate0304** [comment]
I managed to test my code by install setup.py again with my symbulate folder. But when I modified the module, then import the package and tried to test again, it didn't work. I googled and tried %autoreload 2 but it didn't work. I had to install setup.py again and again to test my code. Can you show me a better way ?

**Comment by kevindavisross** [comment]
Dennis, can you give Kien some advice?  I'm not sure if I understand the issue.  Here is the basic process to follow, as I understand it.

- Fork a branch in GitHub
- Clone a copy of the branch to your computer
- Edit the .py files on your computer.  You might need to run `python setup.py install` to implement the changes, but that's just one short line.  But [perhaps `develop` is better](https://stackoverflow.com/questions/19048732/python-setup-py-develop-vs-install).
- After you are satisfied with your edits and tests, push the changes to your branch in GitHub, and send a pull request

Kien, please continue to work on the other changes we discussed yesterday.

**Comment by dlsun** [comment]
Kien, you need to restart Python (or your Jupyter kernel) after you run `python setup.py install`. You cannot simply import the module again because it has already been loaded; Python will not reload a module once it has already been loaded. There is a way you can make it work with the `%autoreload` magic, but I think it's easier to just restart everything.

**Comment by dlsun** [comment]
This issue has been fixed, right? @kevindavisross

**Comment by kevindavisross** [comment]
Yes, I'll close this.
